/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package dentalsoftwareapp;

import java.awt.Color;
import java.awt.Toolkit;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.JTextField;

/**
 *
 * @author Roy
 */
public class SignUp2 extends javax.swing.JFrame {

    /**
     * Creates new form SignUp2
     */
    SignUp signUp = new SignUp();
    private ImageIcon format = null;
    protected String filename = null;
    byte[] person_image = null;
    private Connection con;
    private Statement st;
    private ResultSet rs;
    private PreparedStatement pst;

    public SignUp2() {

        initComponents();
        setLocationRelativeTo(null);
        modifyThis();
        pack();
        try {
            Class.forName("com.mysql.jdbc.Driver");
            con = DriverManager.getConnection("jdbc:mysql://localhost:3306/registerdb", "root", "");
            st = con.createStatement();
        } catch (Exception ex) {
            System.out.println("Error: " + ex);

        }

    }

    private void modifyThis() {

        setTitle("DentaCare Alpha");
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("/resources/teethManager.png")));
        setResizable(false);
        pack();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        txt_name2 = new javax.swing.JLabel();
        lbl_greet2 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        lbl_username2 = new javax.swing.JLabel();
        lbl_password2 = new javax.swing.JLabel();
        lbl_email2 = new javax.swing.JLabel();
        txt_password2 = new javax.swing.JLabel();
        txt_username2 = new javax.swing.JLabel();
        txt_email2 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        lbl_confirm2nd = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jButton2 = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        signup_button = new javax.swing.JButton();
        lbl_confirm2 = new javax.swing.JLabel();
        lbl_img_filepath = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(400, 345));

        jPanel1.setBackground(new java.awt.Color(36, 47, 65));
        jPanel1.setMinimumSize(new java.awt.Dimension(390, 460));
        jPanel1.setPreferredSize(new java.awt.Dimension(390, 460));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txt_name2.setFont(new java.awt.Font("Century Gothic", 3, 22)); // NOI18N
        txt_name2.setForeground(new java.awt.Color(0, 204, 255));
        jPanel1.add(txt_name2, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 10, 280, 30));

        lbl_greet2.setFont(new java.awt.Font("Century", 1, 18)); // NOI18N
        lbl_greet2.setForeground(new java.awt.Color(255, 255, 255));
        lbl_greet2.setText("Hello Dr.");
        jPanel1.add(lbl_greet2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 90, 30));

        jPanel2.setBackground(new java.awt.Color(102, 102, 102));
        jPanel2.setBorder(new javax.swing.border.MatteBorder(null));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbl_username2.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        lbl_username2.setForeground(new java.awt.Color(204, 204, 204));
        lbl_username2.setText("Username");
        jPanel2.add(lbl_username2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, 30));

        lbl_password2.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        lbl_password2.setForeground(new java.awt.Color(204, 204, 204));
        lbl_password2.setText("Password");
        jPanel2.add(lbl_password2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, -1, 30));

        lbl_email2.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        lbl_email2.setForeground(new java.awt.Color(204, 204, 204));
        lbl_email2.setText("Email");
        jPanel2.add(lbl_email2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, -1, 30));

        txt_password2.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        txt_password2.setForeground(new java.awt.Color(0, 204, 255));
        jPanel2.add(txt_password2, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 40, 240, 30));

        txt_username2.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        txt_username2.setForeground(new java.awt.Color(0, 204, 255));
        jPanel2.add(txt_username2, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 0, 240, 30));

        txt_email2.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        txt_email2.setForeground(new java.awt.Color(0, 204, 255));
        jPanel2.add(txt_email2, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 80, 240, 30));
        jPanel2.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 110, 240, 10));
        jPanel2.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 30, 240, 10));
        jPanel2.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 70, 240, 10));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 120, 350, 130));

        lbl_confirm2nd.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        lbl_confirm2nd.setForeground(new java.awt.Color(255, 255, 255));
        lbl_confirm2nd.setText("provided to us are accurate");
        jPanel1.add(lbl_confirm2nd, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, -1, 30));

        jPanel3.setForeground(new java.awt.Color(0, 0, 0));

        jButton2.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jButton2.setForeground(new java.awt.Color(0, 0, 0));
        jButton2.setText("I want to make changes");
        jButton2.setBorder(null);
        jButton2.setBorderPainted(false);
        jButton2.setContentAreaFilled(false);
        jButton2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton2);

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 270, 180, 30));

        jPanel4.setBackground(new java.awt.Color(51, 153, 255));
        jPanel4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        signup_button.setBackground(new java.awt.Color(51, 153, 255));
        signup_button.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        signup_button.setForeground(new java.awt.Color(204, 204, 204));
        signup_button.setText("Sign Up");
        signup_button.setBorder(null);
        signup_button.setBorderPainted(false);
        signup_button.setContentAreaFilled(false);
        signup_button.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        signup_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                signup_buttonActionPerformed(evt);
            }
        });
        jPanel4.add(signup_button);

        jPanel1.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 270, 90, 30));

        lbl_confirm2.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        lbl_confirm2.setForeground(new java.awt.Color(255, 255, 255));
        lbl_confirm2.setText("Before we sign you up, please make sure that all the details you ");
        jPanel1.add(lbl_confirm2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, -1, 30));

        lbl_img_filepath.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        lbl_img_filepath.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.add(lbl_img_filepath, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 260, 360, 30));

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:

        signUp.show();
        this.dispose();

        //String name = txt_name2.getText();
        String username = txt_username2.getText();
        String password = txt_password2.getText();
        String email = txt_email2.getText();

        /*  if (name.endsWith(",")) {
         String removeComa = signUp.txt_name.getText().trim();
         txt_name2.setText(removeComa);
         }
         */
        signUp.txt_name.setText("Please re-enter your full name");
        signUp.txt_username.setText(username);
        signUp.txt_password.setText(password);
        signUp.txt_email.setText(email);


    }//GEN-LAST:event_jButton2ActionPerformed

    private void signup_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_signup_buttonActionPerformed
        // TODO add your handling code here:

        // this needs more analysis and study! -ROY
        // prone to bugs and errors
        JTextField field = new JTextField();
        field.setColumns(50);
        field.setForeground(Color.MAGENTA);

        Object[] options = {"Register Me",
            "Cancel"};
        int userOption = JOptionPane.showOptionDialog(null, field,
                "To activate this software, please enter the license key provided that we provided to you.",
                JOptionPane.YES_NO_OPTION,
                JOptionPane.QUESTION_MESSAGE,
                new ImageIcon(getClass().getResource("/resources/key.png")),
                options,
                options[0]);

        if (userOption == 0) {
            {
                try {

                    String code = field.getText();

                    String getLicense = "SELECT `License Key` FROM `keytbl` WHERE `License Key` = '" + code + "' ";
                    rs = st.executeQuery(getLicense);

                    int count = 0;
                    while (rs.next()) {
                        count += 1;
                    }
                    if (count == 1) {

                        try {
                            Thread.sleep(1000);

                            JOptionPane.showMessageDialog(this, "Software activation successful!");
                            System.out.println("Success verification 2");
                            String addDentist = "INSERT INTO `registertbl`(`Full Name`, `Username`, `Password`, `Email`) VALUES (?,?,?,?)";

                            pst = con.prepareStatement(addDentist);

                            pst.setString(1, txt_name2.getText());
                            pst.setString(2, txt_username2.getText());
                            pst.setString(3, txt_password2.getText());
                            pst.setString(4, txt_email2.getText());
                            pst.execute();

                            System.out.println("data inserted!");
                            String disposeKey = "DELETE FROM `keytbl` WHERE `License Key` = ?";
                            try {
                                pst = con.prepareStatement(disposeKey);
                                pst.setString(1, field.getText());
                                pst.execute();
                                System.out.println("key disposed!");
                                JOptionPane.showMessageDialog(null, "License was successfully registered to your account. Please keep a copy of it for future reference.");

                            } catch (Exception e) {

                                JOptionPane.showMessageDialog(null, e);
                            }

                            this.dispose();
                            Login login = new Login();
                            login.setVisible(true);
                        } catch (Exception ex) {

                        }
                    } else {
                        Thread.sleep(1000);
                        JOptionPane.showMessageDialog(field, "Invalid license key");

                    }

                } catch (Exception ex) {

                }
                // revisee!!

            }
        } else {

        }


    }//GEN-LAST:event_signup_buttonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;

                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SignUp2.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SignUp2.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SignUp2.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SignUp2.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SignUp2().setVisible(true);

            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    public javax.swing.JPanel jPanel4;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    public javax.swing.JLabel lbl_confirm2;
    public javax.swing.JLabel lbl_confirm2nd;
    public javax.swing.JLabel lbl_email2;
    private javax.swing.JLabel lbl_greet2;
    private javax.swing.JLabel lbl_img_filepath;
    public javax.swing.JLabel lbl_password2;
    public javax.swing.JLabel lbl_username2;
    private javax.swing.JButton signup_button;
    public javax.swing.JLabel txt_email2;
    public javax.swing.JLabel txt_name2;
    public javax.swing.JLabel txt_password2;
    public javax.swing.JLabel txt_username2;
    // End of variables declaration//GEN-END:variables
}
