package dentalsoftwareapp;

import static java.awt.image.ImageObserver.HEIGHT;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import static javax.swing.JOptionPane.OK_CANCEL_OPTION;
import static javax.swing.JOptionPane.PLAIN_MESSAGE;
import static javax.swing.JOptionPane.QUESTION_MESSAGE;
import static javax.swing.JOptionPane.YES_NO_OPTION;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author dyne
 */
public class Terms extends javax.swing.JDialog {

    /**
     * Creates new form Terms
     */
    public Terms(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        this.setDefaultCloseOperation(DO_NOTHING_ON_CLOSE);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jPanel1 = new javax.swing.JPanel();
        terms_and_conditions = new javax.swing.JCheckBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                formMouseEntered(evt);
            }
        });
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jScrollPane1.setBackground(new java.awt.Color(153, 153, 153));

        jTextArea1.setEditable(false);
        jTextArea1.setBackground(new java.awt.Color(51, 51, 51));
        jTextArea1.setColumns(20);
        jTextArea1.setFont(new java.awt.Font("Lucida Fax", 0, 14)); // NOI18N
        jTextArea1.setForeground(new java.awt.Color(153, 153, 153));
        jTextArea1.setRows(5);
        jTextArea1.setText("Terms and conditions before using this software \n\nBefore using this software, you must agree to the following statements\n\n1) Intellectual Property\nDentaCare remains and shall remain exclusively the property of its makers, \nComputer Scientist Students of AMA Computer College of Parañaque. \nSee students\n\n1.1\nTherefore, it is only just to have all the rights reserved in this software for \nthese students who were and the only ones who made this software. \n\n1.2\nSuch support from any other software developers, engineers, \nprogrammers and or other professions outside AMA Computer College\nwere not entertained/received.\nTherefore, all credits are to be directed only, and strictly only, to its \nmakers who are/were the students of AMA Computer College, Parañaque.\n\n1.3\nDentaCare was created for the sole purpose of Computer studies brought \nabout by Computer Science, Software Engineering Course. Without \nexemption, this software aims to let the students of AMA Computer College, \nParañaque build systematized programs that target dentists who would \nwant to manage their patients more efficiently.\nSee about app.\n\n1.3.1\nHence, DentaCare must be fairly used only for educational purpose and \npersonal use. \n\n1.3.2\nIn addition, DentaCare is exclusively designed only for dentists and shall \nremain strictly to its sole premises.\n\n1.4\nDistribution of DentaCare without grant, intended or unintended, is strictly\nprohibited and will resort to an absolute punishment under the Law. \n\n2) Liability \nUser/s of this software must be aware of possible consequences of using \nDentaCare for their personal use. \n\n2.1\nDentaCare was made by students who promised to help dentists through \nthis app. (See 1.3) \n\n2.1.2\nThus, any damage/s problem/s that this software may bring to its users will \nnot be directed to its makers but to the user who agreed to all propositions \nbeforehand.\n\n2.2\n\n");
        jTextArea1.setCaretPosition(0);
        jTextArea1.setMinimumSize(new java.awt.Dimension(476, 500));
        jTextArea1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jTextArea1MouseEntered(evt);
            }
        });
        jScrollPane1.setViewportView(jTextArea1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 510, 400));

        jPanel1.setBackground(new java.awt.Color(51, 51, 51));
        jPanel1.setOpaque(false);
        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 410, 510, 40));

        terms_and_conditions.setBackground(new java.awt.Color(51, 51, 51));
        terms_and_conditions.setFont(new java.awt.Font("Open Sans", 0, 13)); // NOI18N
        terms_and_conditions.setForeground(new java.awt.Color(192, 64, 34));
        terms_and_conditions.setText("I have read accordingly and firmly accept and agree to all terms and conditions.");
        terms_and_conditions.setFocusPainted(false);
        terms_and_conditions.setOpaque(true);
        terms_and_conditions.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                terms_and_conditionsActionPerformed(evt);
            }
        });
        getContentPane().add(terms_and_conditions, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 400, 510, 50));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseEntered
        // TODO add your handling code here:


    }//GEN-LAST:event_formMouseEntered

    private void jTextArea1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextArea1MouseEntered
        // TODO add your handling code here:
        if (terms_and_conditions.isSelected()) {

            SignUp signup = new SignUp();
            signup.chkbox_agree.setEnabled(true);
            signup.chkbox_agree.setSelected(true);
            this.setVisible(false);
            
        }

    }//GEN-LAST:event_jTextArea1MouseEntered

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        // TODO add your handling code here:

    }//GEN-LAST:event_formWindowClosed

    private void terms_and_conditionsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_terms_and_conditionsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_terms_and_conditionsActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        // TODO add your handling code here:
        int options = JOptionPane.showConfirmDialog(Terms.this, "You must first agree to the terms and conditions stated hereby", "Check the box after reading", PLAIN_MESSAGE, QUESTION_MESSAGE, new ImageIcon(getClass().getResource("/resources/nerd.png")));
        if (options == JOptionPane.CANCEL_OPTION) {

        } else {

        }
    }//GEN-LAST:event_formWindowClosing

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Terms.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Terms.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Terms.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Terms.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Terms dialog = new Terms(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    protected javax.swing.JCheckBox terms_and_conditions;
    // End of variables declaration//GEN-END:variables
}
